CREATE TABLE value_balance_questions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    axis VARCHAR(20) NOT NULL,
    left_label VARCHAR(100) NOT NULL,
    right_label VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_value_balance_questions PRIMARY KEY (id),
    CONSTRAINT chk_value_balance_questions_axis CHECK (
        axis IN ('LOVE', 'LIFESTYLE', 'COMM', 'DECISION', 'SOCIAL', 'PRIORITY', 'TONE', 'TASTE')
    ),
    CONSTRAINT chk_value_balance_questions_labels CHECK (left_label <> right_label)
);

CREATE TABLE value_balance_answers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    chosen_side VARCHAR(5) NOT NULL,
    answered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_value_balance_answers PRIMARY KEY (id),
    CONSTRAINT fk_value_balance_answers_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_value_balance_answers_question
        FOREIGN KEY (question_id) REFERENCES value_balance_questions(id),
    CONSTRAINT chk_value_balance_answers_side CHECK (chosen_side IN ('LEFT', 'RIGHT'))
);

CREATE INDEX idx_value_balance_answers_user_answered
    ON value_balance_answers (user_id, answered_at);
CREATE INDEX idx_value_balance_answers_user_question_answered
    ON value_balance_answers (user_id, question_id, answered_at);

CREATE TABLE user_value_axis_scores (
    user_id BIGINT NOT NULL,
    axis VARCHAR(20) NOT NULL,
    score DECIMAL(5,4) NOT NULL DEFAULT 0,
    sample_count INT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_value_axis_scores PRIMARY KEY (user_id, axis),
    CONSTRAINT fk_user_value_axis_scores_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_value_axis_scores_axis CHECK (
        axis IN ('LOVE', 'LIFESTYLE', 'COMM', 'DECISION', 'SOCIAL', 'PRIORITY', 'TONE', 'TASTE')
    ),
    CONSTRAINT chk_user_value_axis_scores_score CHECK (score BETWEEN -1.0000 AND 1.0000),
    CONSTRAINT chk_user_value_axis_scores_sample_count CHECK (sample_count >= 0)
);

INSERT INTO value_balance_questions (axis, left_label, right_label) VALUES
('LOVE', '스킨십은 초반부터 자연스럽게', '충분히 친해진 후에'),
('LOVE', '연락은 자주 주고받는 편', '필요할 때만 편하게'),
('LOVE', '다투면 바로 대화로 푸는 편', '시간을 두고 진정한 후 대화'),
('LOVE', '애정표현은 말로 자주', '행동으로 은근히'),
('LOVE', '기념일은 꼭 챙기는 편', '편하게 넘기는 편'),
('LOVE', '데이트 비용은 반반', '그때그때 유동적으로'),
('LOVE', '연애 초반엔 천천히', '확 빠지는 편'),
('LOVE', '상대의 과거 연애사가 궁금한 편', '굳이 안 궁금한 편'),
('LOVE', '애정표현은 사람들 앞에서도', '둘이 있을 때만'),
('LOVE', '질투가 나면 티내는 편', '티 안 내는 편'),
('LOVE', '연애 중에도 각자 시간 존중', '최대한 함께'),
('LOVE', '만남은 계획적으로', '자연스러운 만남 선호'),
('LOVE', '이상형보다 끌림', '끌림보다 조건'),
('LIFESTYLE', '아침형 인간', '저녁형 인간'),
('LIFESTYLE', '집에서 쉬는 게 최고', '밖으로 나가야 힘이 남'),
('LIFESTYLE', '계획적인 하루', '즉흥적인 하루'),
('LIFESTYLE', '미니멀리스트', '맥시멀리스트'),
('LIFESTYLE', '운동은 매일 챙기는 편', '마음 내킬 때'),
('LIFESTYLE', '여행은 계획 빡빡하게', '발길 닿는 대로'),
('LIFESTYLE', '주말은 몰아서 자기', '평소처럼 일찍 일어나기'),
('LIFESTYLE', '청소는 그때그때', '몰아서 한번에'),
('LIFESTYLE', '새로운 곳 탐방', '익숙한 단골집'),
('LIFESTYLE', '카페인 없인 못 사는 편', '딱히 상관없음'),
('LIFESTYLE', '옷차림은 편한 게 최고', '꾸미는 게 좋음'),
('LIFESTYLE', '강아지파', '고양이파'),
('LIFESTYLE', '여름', '겨울'),
('COMM', '할 말은 바로 하는 편', '돌려서 말하는 편'),
('COMM', '전화 통화 선호', '문자/메시지 선호'),
('COMM', '리액션이 큰 편', '잔잔한 편'),
('COMM', '먼저 연락하는 편', '답장하는 편'),
('COMM', '진지한 대화가 좋음', '가벼운 농담이 편함'),
('COMM', '속마음을 잘 드러내는 편', '잘 안 드러내는 편'),
('COMM', '칭찬은 직설적으로', '은근하게'),
('COMM', '갈등 상황에서 할 말은 하는 편', '일단 참는 편'),
('COMM', '대화 중 침묵이 편함', '침묵이 어색함'),
('COMM', '이모티콘 많이 쓰는 편', '텍스트 위주'),
('COMM', '목소리 톤이 밝은 편', '차분한 편'),
('COMM', '대화 주도하는 편', '들어주는 편'),
('COMM', '드립/개그형 유머', '진지한 위트형 유머'),
('DECISION', '직관적으로 결정', '꼼꼼히 따져보고 결정'),
('DECISION', '새로운 시도가 좋음', '검증된 것 선호'),
('DECISION', '위험을 감수하더라도 도전', '안전한 선택'),
('DECISION', '계획을 세우고 실행', '일단 해보고 조정'),
('DECISION', '완벽하게 끝내는 편', '일단 마무리하고 넘어가는 편'),
('DECISION', '혼자 결정하는 편', '주변에 의견 구하는 편'),
('DECISION', '큰 그림을 먼저 봄', '디테일부터 챙김'),
('DECISION', '변화에 빠르게 적응', '익숙해질 시간 필요'),
('DECISION', '마감 전에 미리 끝내는 편', '닥쳐서 하는 편'),
('DECISION', '데이터/근거 중시', '감/경험 중시'),
('DECISION', '여러 가지 동시에', '한 번에 하나씩'),
('DECISION', '결정은 빠르게', '신중하게 오래'),
('DECISION', '밀어붙이는 편', '돌다리도 두들겨보는 편'),
('SOCIAL', '친구는 적고 깊게', '많고 넓게'),
('SOCIAL', '모임에서 주로 말하는 편', '듣는 편'),
('SOCIAL', '새로운 사람 만나는 게 즐거움', '익숙한 사람이 편함'),
('SOCIAL', '큰 모임 좋아함', '소수의 자리 선호'),
('SOCIAL', '처음 보는 사람과도 스스럼없음', '어색함이 있음'),
('SOCIAL', '인맥 넓히는 걸 즐김', '굳이 안 늘려도 됨'),
('SOCIAL', '그룹 여행', '단둘이 여행'),
('SOCIAL', 'SNS 자주 하는 편', '거의 안 함'),
('SOCIAL', '힘들 때 사람들과 어울리며 풀기', '혼자만의 시간으로 풀기'),
('SOCIAL', '모임/행사 주최하는 편', '참석만 하는 편'),
('SOCIAL', '오랜 친구가 편함', '새 인연이 설렘'),
('SOCIAL', '연락은 내가 먼저', '상대가 먼저 해주길'),
('SOCIAL', '단체 채팅방 활발히', '필요할 때만'),
('PRIORITY', '커리어 성장', '워라밸'),
('PRIORITY', '돈보다 시간', '시간보다 돈'),
('PRIORITY', '안정적인 직장', '도전적인 커리어'),
('PRIORITY', '현재를 즐기는 삶', '미래를 준비하는 삶'),
('PRIORITY', '가족 중심', '개인 중심'),
('PRIORITY', '경험에 투자', '소유에 투자'),
('PRIORITY', '인정받는 게 중요', '스스로 만족이 중요'),
('PRIORITY', '목표 지향적인 삶', '흘러가는 대로'),
('PRIORITY', '저축이 우선', '지금의 행복이 우선'),
('PRIORITY', '자기계발에 진심', '여유롭게 즐기는 삶'),
('PRIORITY', '명예/성취 지향', '평온/안정 지향'),
('PRIORITY', '큰 성공 한 번', '꾸준한 작은 행복'),
('PRIORITY', '이직/변화 두렵지 않음', '한 곳에서 오래'),
('TONE', '장난기 많은 편', '진중한 편'),
('TONE', '슬픈 영화 보면 눈물', '덤덤한 편'),
('TONE', '감정이 얼굴에 다 드러남', '티가 잘 안 남'),
('TONE', '리액션 크게', '조용히 공감'),
('TONE', '드립/농담형 유머', '재치있는 관찰형 유머'),
('TONE', '화가 나면 표현하는 편', '삭히는 편'),
('TONE', '애교 있는 편', '무뚝뚝한 편'),
('TONE', '기분이 티나는 편', '항상 일정한 편'),
('TONE', '웃음이 많은 편', '잔잔한 미소'),
('TONE', '감성적인 노래 선호', '신나는 노래 선호'),
('TONE', '칭찬 들으면 티내며 좋아함', '담담하게 받음'),
('TONE', '서운하면 바로 말함', '혼자 삭히는 편'),
('TONE', '로맨틱한 이벤트 좋아함', '소소한 게 좋음'),
('TASTE', '커피', '차'),
('TASTE', '산', '바다'),
('TASTE', '매운맛', '순한맛'),
('TASTE', '영화관', '집에서 스트리밍'),
('TASTE', '책', '영상'),
('TASTE', '아침밥 챙겨먹기', '거르는 편'),
('TASTE', '계획 없는 드라이브', '목적지 있는 외출'),
('TASTE', '겨울엔 눈 구경', '겨울엔 실내'),
('TASTE', '반찬은 이것저것', '한 가지 집중'),
('TASTE', '노래방에서 신나는 노래', '발라드'),
('TASTE', '캠핑/자연', '호캉스/도심'),
('TASTE', '아이스 아메리카노', '따뜻한 라떼'),
('TASTE', '게임으로 스트레스 풀기', '운동으로 스트레스 풀기');
